# @sidebar midi
class SAM2695
  DEFAULT_BAUD: Integer

  @uart: UART_MIDI

  def self.new: (Integer tx_pin, ?Integer rx_pin, ?Integer baud) -> instance
  def transport_id: () -> Integer
  def send_packet: (Integer cable, Integer cin, Integer midi1, Integer midi2, Integer midi3) -> Integer
  def bytes_available: () -> Integer
  def read_available: () -> nil
  def connected?: () -> bool
  def open_device: () -> (SAM2695 | nil)
  def status: () -> Integer
  def device_info: () -> (Hash[Symbol, Integer] | nil)
  def tx_pin: () -> Integer
  def rx_pin: () -> Integer
  def start_input: () -> Integer
  def stop_input: () -> nil
  def input_running?: () -> bool
end
